title: Merra Felice Antonio
url: "http://merrafelice.github.io"
#baseurl: "/researcher"
remote_theme: ankitsultana/researcher@gem

markdown: kramdown
#ins_logo: "./bits-logo.png"
#remote_theme: ankitsultana/researcher@gem
tracking_id: #

footer: yes
footer_url: "http://github.com/merrafelice"
footer_text: "Page design by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "Home"
   link: "/"
 - name: "Resume"
   link: "resume.pdf"
 - name: "Contact"
   link: "contact"
