title: "Felice Antonio Merra"
url: "http://merrafelice.github.io"
baseurl: ""

remote_theme: ankitsultana/researcher@gem

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: UA-145520672-1

footer: yes
footer_url: "https://github.com/ankitsultana"
footer_text: "Page design by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "Home"
   link: "http://merrafelice.github.io"
 - name: "Resume"
   link: "resume.pdf"

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# Tags

description: "Felice Antonio Merra's Personal Blog. Follow my research activity! @merrafelice"
author: "Felice Antonio Merra"

twitter:
  username: merrafelice
  card: "Felice Antonio Merra's Personal Blog. Follow my research activity! @merrafelice"

image: /profile.jpg
#image: /felice-merra.png
lang: english
